### ISSUE TITLE
ERROR: Obsidian Utilities[Write Text File]

### ISSUE THREAD

**Issue by yashmosh** [macedotavares/obsidian-utilities#15]
Hi Senhor,

I have installed the "Obsidian Utilities" plug-in, but I get the following error message when I use "dj" command:

ERROR: Obsidian Utilities[Write Text File] You can’t save the file “2021-04-22.md” because the volume “Macintosh HD” is read-only."

I was hoping you could direct me on the right path.

Thanks

**Comment by yashmosh** [comment]
I managed to solve the issue. The problem was that I did not set the initial parameters. Once I did that, it worked perfectly. 

So I close this issue but leave the answer here for anyone else facing the same problem.

**Comment by macedotavares** [comment]
I'm sorry for being ridiculously late. Glad you solved it anyway. Cheers.
