### ISSUE TITLE
daily journal opens but note doesn't get appended

### ISSUE THREAD

**Issue by mgeduld** [macedotavares/obsidian-utilities#18]
If I evoke Alfred and type `dj this is a test`, my daily note opens in Obsidian but no text gets added. I see a notification that says the file has been opened, and there's no error message. It just silently fails. 

I'm using the latest version of Obsidian, Alfred 4, and Mac OS Big Sur.

**Comment by mgeduld** [comment]
My vault is in an iCloud folder.

**Comment by mgeduld** [comment]
[16:03:46.243] ERROR: Obsidian Utilities[Write Text File] Unable to write file '/daily/2021-07-15.md' as parent folder does not exist

Yet it's able to find this file and display it.

**Comment by macedotavares** [comment]
Can you share a screenshot of your environment variables?

**Comment by mgeduld** [comment]
After messing with the vault_path var, I was able to get it to work.
