### ISSUE TITLE
Hard coded notes path in fallback search

### ISSUE THREAD

**Issue by heliostatic** [macedotavares/obsidian-utilities#2]
In the final step of the fallback search, the file path is:
`~/Dropbox/Notas/Notas Diárias/{var:daily_note}`
Instead of using the Vault path, as in the `journal` workflow:
`~{var:vault_path}/{var:daily_folder}/{var:date}.md`

**Comment by macedotavares** [comment]
What a dumb mistake. I'll fix that for he upcoming release. Thanks!
