### ISSUE TITLE
search: cannot import name '_psutil_osx' from partially initialized module 'psutil' (most likely due to a circular import) 

### ISSUE THREAD

**Issue by carmensandoval** [macedotavares/obsidian-utilities#3]
Hi 👋 

I seem to have a problem with the search utility. The debug log shows that one of the scripts is unable to fully load the psutil module. I wonder if this is due to my using Anaconda as my Python environment.

Any idea what I coulld do to fix this? Thanks!

![Alfred Preferences_20210110_14 48 23](https://user-images.githubusercontent.com/10520084/104137616-1256c700-5353-11eb-947a-2aa2f55e9ded.gif)

**Comment by macedotavares** [comment]
I'm inclined to say yes, Anaconda must be causing it, but I'll have to look into it in the next couple of days. 

Does this happen when running other actions that include python scripts, like Cmd+Shift+L?

**Comment by macedotavares** [comment]
The action no longer uses python. It should work now. Please download [v2.0.2](https://github.com/macedotavares/obsidian-utilities/releases/download/v2.0.2/Obsidian.Utilities.alfredworkflow).

**Comment by macedotavares** [comment]
I'm closing this. If something goes wrong now, it will have nothing to do with this matter.
