### ISSUE TITLE
Error executing task flow

### ISSUE THREAD

**Issue by heliostatic** [macedotavares/obsidian-utilities#9]
<img width="436" alt="CleanShot 2021-01-19 at 17 08 25@2x" src="https://user-images.githubusercontent.com/70898/105099229-55164e80-5a79-11eb-8e7b-08ec6a14aba1.png">

Ah, now the issue is `zsh: ./append_to_heading.py: bad interpreter: /usr/bin/python3: no such file or directory` because my python is at `/usr/local/bin/python3` -- this is the default for `homebrew` installation -- how is yours installed, and maybe I'll just switch to/emulate that? For now, `ln -s` should fix it.

**Comment by macedotavares** [comment]
Man, that's nasty. I pointed to /usr/bin/python3 because that's the default macOS interpreter, and the only one I *thought* would be present in every machine. Now I'm afraid a lot more people will face the same issue. 🤦‍♂️

**Comment by heliostatic** [comment]
Two follow ups:
1. I'm on Mojave still, so no python3 in in /usr/bin
2. Can't symlink anything there because of System Integrity Protection.

Current thought is to just update to Catalina at least. You should probably make a note about 10.15 or above being required :)

**Comment by macedotavares** [comment]
Ok, that settles it. I'm afraid most of the python scripts would be hard to adapt, because python 2.* has very sucky Unicode support. So 10.15+ it must be. 

Thanks for your help!
